name: mobile_dapp
description: An example how to create a mobile dApp
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  algorand_dart: 0.0.2-beta.8
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  http: ^0.13.4
  qr_flutter: ^4.0.0
  url_launcher: ^6.0.12
  walletconnect_dart:
    path: ../../
  web3dart: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
